// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GenApi
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Globalization;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\src\Austin.Linode\GenApi\SpecGen.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class SpecGen : SpecGenBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing System.Globalization;\r\n" +
                    "\r\nnamespace Austin.Linode\r\n{\r\npartial class LinodeClient\r\n{\r\n");
            
            #line 16 "C:\src\Austin.Linode\GenApi\SpecGen.tt"

int[] ver = new int[4];
string[] splits = SPEC.Version.Split('.');
for (int i = 0; i < splits.Length; i++)
{
	ver[i] = int.Parse(splits[i], CultureInfo.InvariantCulture);
}

            
            #line default
            #line hidden
            this.Write("\tpublic readonly Version GeneratedApiVersion = new Version(");
            
            #line 24 "C:\src\Austin.Linode\GenApi\SpecGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ver[0]));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 24 "C:\src\Austin.Linode\GenApi\SpecGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ver[1]));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 24 "C:\src\Austin.Linode\GenApi\SpecGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ver[2]));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 24 "C:\src\Austin.Linode\GenApi\SpecGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ver[3]));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 25 "C:\src\Austin.Linode\GenApi\SpecGen.tt"

    foreach (var meth in SPEC.Methods.OrderBy(kvp => kvp.Key))
    {
		if (meth.Key == "api.spec")
			continue; //this is created manually, otherwise there is a chicken/egg problem

		Type returnType = typeof(void);
		if (mReturnType.ContainsKey(meth.Key))
			returnType = mReturnType[meth.Key];

            
            #line default
            #line hidden
            this.Write("\tpublic ");
            
            #line 35 "C:\src\Austin.Linode\GenApi\SpecGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrettyPrintType(returnType)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 35 "C:\src\Austin.Linode\GenApi\SpecGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName(meth.Key)));
            
            #line default
            #line hidden
            this.Write("(\r\n");
            
            #line 36 "C:\src\Austin.Linode\GenApi\SpecGen.tt"

		int paramCount = meth.Value.Parameters.Count();
		PushIndent(new string(' ', 12));
		foreach (var param in SortParams(meth.Value.Parameters))
		{
			Write(ParamDec(param.Key, param.Value));
			if (--paramCount != 0)
			{
				WriteLine(", ");
			}
		}
		PopIndent();

            
            #line default
            #line hidden
            this.Write("\t)\r\n\t{\r\n");
            
            #line 51 "C:\src\Austin.Linode\GenApi\SpecGen.tt"

		if (meth.Value.HasParameters)
			WriteLine("var myParams = new Dictionary<string, string>();");
		foreach (var param in SortParams(meth.Value.Parameters))
		{
			if (!param.Value.Required)
			{

            
            #line default
            #line hidden
            this.Write("\t\tif (");
            
            #line 59 "C:\src\Austin.Linode\GenApi\SpecGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(param.Key));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n");
            
            #line 60 "C:\src\Austin.Linode\GenApi\SpecGen.tt"

			}

            
            #line default
            #line hidden
            this.Write("\t\tmyParams.Add(\"");
            
            #line 63 "C:\src\Austin.Linode\GenApi\SpecGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(param.Key));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 63 "C:\src\Austin.Linode\GenApi\SpecGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(param.Key));
            
            #line default
            #line hidden
            
            #line 63 "C:\src\Austin.Linode\GenApi\SpecGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ToStringPostfix(param.Value)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 64 "C:\src\Austin.Linode\GenApi\SpecGen.tt"

		}
		if (returnType != typeof(void))
		{
			Write("return ");
		}

            
            #line default
            #line hidden
            this.Write("\t\tGetResponse< ");
            
            #line 71 "C:\src\Austin.Linode\GenApi\SpecGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(returnType == typeof(void) ? "object" : PrettyPrintType(returnType)));
            
            #line default
            #line hidden
            this.Write(" >(\"");
            
            #line 71 "C:\src\Austin.Linode\GenApi\SpecGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(meth.Key));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 71 "C:\src\Austin.Linode\GenApi\SpecGen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(meth.Value.HasParameters ? "myParams" : "null"));
            
            #line default
            #line hidden
            this.Write(");\r\n\t}\r\n");
            
            #line 73 "C:\src\Austin.Linode\GenApi\SpecGen.tt"

    }

            
            #line default
            #line hidden
            this.Write("}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class SpecGenBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
