//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austin.Libode.IntegrationTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Austin.Libode.IntegrationTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ERRORARRAY&quot;:[],&quot;DATA&quot;:[{&quot;HOST_MESSAGE&quot;:&quot;&quot;,&quot;HOST_START_DT&quot;:&quot;&quot;,&quot;ENTERED_DT&quot;:&quot;2011-05-09 03:24:26.0&quot;,&quot;HOST_FINISH_DT&quot;:&quot;&quot;,&quot;JOBID&quot;:4426423,&quot;LABEL&quot;:&quot;System Boot - My Ubuntu 10.04 LTS Profile&quot;,&quot;HOST_SUCCESS&quot;:&quot;&quot;,&quot;ACTION&quot;:&quot;linode.boot&quot;,&quot;DURATION&quot;:&quot;&quot;,&quot;LINODEID&quot;:94044},{&quot;HOST_MESSAGE&quot;:&quot;&quot;,&quot;HOST_START_DT&quot;:&quot;&quot;,&quot;ENTERED_DT&quot;:&quot;2011-05-09 03:24:26.0&quot;,&quot;HOST_FINISH_DT&quot;:&quot;&quot;,&quot;JOBID&quot;:4426422,&quot;LABEL&quot;:&quot;System Shutdown&quot;,&quot;HOST_SUCCESS&quot;:&quot;&quot;,&quot;ACTION&quot;:&quot;linode.shutdown&quot;,&quot;DURATION&quot;:&quot;&quot;,&quot;LINODEID&quot;:94044},{&quot;HOST_MESSAGE&quot;:&quot;&quot;,&quot;HOST_START_DT&quot;:&quot;2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListJobs {
            get {
                return ResourceManager.GetString("ListJobs", resourceCulture);
            }
        }
    }
}
